src/App.scss

**Issue:**
The background colour of each row doesn't go all the way to the fixed columns.
There is a gap between the first and second column.
title row looks exactly the same as the body of the table.
**Solution:**
Fix only the first column and leave the second column unfixed.
Change the background colour of the first column, so the background colour across each row is consistent.
Give the title a different background colour and bold the title text.
_Notes:_
To fix the position of the second column, we need to know the width of first column during runtime. This is difficult to achieve now but it is something that user wants. Therefore, we will still need to implement it in the future.
**Risk: ** /
Annie, Eileen, Dave, Yujia, Kevin

[CMLG-007] fix the first column

---

src/App.scss

Issue:
When scrolling horizontally the entire webpage moves, when we only want the table to in a smaller screen.
Solution:
Changed the css for the container for the table tag to overflow-x: auto !important.
Fixed the problem with z-index of the table headers.
Risk:
The !important flag may cause issues, but not entirely sure.
Reviewed by: Yujia, Kevin, Dave, Emily, Eileen

[CMLG-001] Enabled responsive horizontal scroll of the table grid

---

src/components/SearchPage.js
src/components/Table.js
src/components/css/Table.css

**Issue:**
SearchPage is passing names of headers to the Table component, Table component no longer needs to store this information.
The header name "Portugues" and "Turkce" are not the same as the one in the excel sheet that the user provides.
**Solution:**
Table component is now displaying the headers of the table using the props passed by the SearchPage component.
Changing Portugues to Português and Turkce to Türkçe in order to match the excel sheet.
**Risk:**
/
Annie, Eileen, Yujia, Kevin, Dave

[CMLG-011] Sort table when the user clicks the column 

---

.gitignore
src/components/Table.js

**Issue:**
When the user checks/unchecks a box in the selectColumn component, the table be modified to display only columns that the user selects.
**Solution:**
Column selected status is passed from the SearchPage component to the Table component. If a column is selected, the "display" CSS of all table cells in that column is changed to "table-cell", otherwise it is set to be "none".
**Risk:**
/
Annie, Eileen, Yujia, Kevin, Dave

[CMLG-011] Display only columns selected 

---

src/components/Table.js

**Issue:** 
We wanted to implement instant search, which works like this: the words that the user is searching for (input into the search bar) are displayed on the page real time. Clicking the search icon after typing the search word (e.g. Google) is not required as search operation happens real time.
Also, we changed our backend API so our app didn't work properly. 
**Solution:** 
Used componentDidUpdate() to change the URL that is fetched every time when the search word is changed. For example, when searching for the word virus, the URL will change from https://cmlgbackend.wdcc.co.nz/api/translations?sequence=1596773281500&word= to https://cmlgbackend.wdcc.co.nz/api/translations?sequence=1596773281500&word=virus.
In order to make the app work with the new backend API, we changed the URL …

[CMLG-011] Instant Search

---

src/components/SearchPage.js
src/components/Table.js

Issue:
The table doesn't have a word property so the search word is not passed to Table.
When the website first loads, the word is null but we don't want to pass null as the search word to the API. Instead, we want the API to returns the first ten rows.
Solution:
Pass a property words to the table component.
Check if the website is loading, if it is, call /translations?sequence=xxx end point instead of /translations?sequence=xxx?word=null
Risk:
/
Reviewed by:
Annie, Dave, Eileen, Yujia, Kevin

[CMLG-011] fix the displaying data issue with new API

---

src/components/Table.js

**Issue:**
Frontend gets responses in random order, the frontend needs to decide which response to process and put on the table. For example, when the user searches for "u" and "p", the response for "up" comes first. When the response for "u" arrives, the frontend needs to realise this response is no longer needed and delete it.
**Solution:**
Because the response contains a sequence number, the Table component contains the sequence of the currently displayed response. When receiving the next response, the Table component looks at the sequence number, and only displays the data if its sequence is larger than the current one.
**Risk:**
/
Annie, Eileen, Dave, Kevin, Yujia

[CMLG-011] Only display the most recent search result

---

src/components/SearchPage.js
src/components/css/SearchPage.css

**Issue:**
Scrolling bar is put on the browser, when the user scrolls the page to the right, all components including the search bar and select component are scrolled.
**Solution:**
The table cannot have "overflow" CSS on it. Therefore, change the display of searchPage to be "grid", the search page component contains two rows. Searchbar and select components are in the first row. The table is in the second row. Change the overflow of the div around the table to be "scroll".
**Risk:**
When scrolling the table vertically, the header moves as well.
Annie, Dave, Eileen, Yujia, Kevin

[CMLG-011] Put the scroll bar on table only

---

src/components/SearchPage.js
src/components/css/Table.css

**Issue:**
When sorting columns, there is a small arrow appearing beside the header clicked, indicating the sorting order. If the width of the header is not enough, the arrow goes to the next line.
**Solution:**
Add CSS style "white-space: nowrap" to force the arrow to be on the same line.
**Risk:**
As the width of the header is not enough for the arrow to be on the same line, when the arrow appears, the width of the header will get automatically larger to fit both words and arrow.
Annie, Eileen, Kevin, Dave, Yujia

[CMLG-011] Fix responsive issue when sorting columns

---

package.json
src/components/SearchPage.js

**Issue:**
The frontend is sending a request to the backend every time the user types something, which quickly reaches the API rate limit.
**Solution:**
Only changes the state if the user doesn't type for 180 ms.
**Risk:**
need to run npm install again as a new library is downloaded for debouncing. 
Annie, Dave, Eileen, Kevin, Yujia

[CMLG-012] delay onChange event when user types something in the search box

---

src/components/SearchPage.js
src/components/Table.js

**Issue:**
To allow users to choose between 10 rows/all and which page to look at, a Toggle Buttons component and a Table Pagination component need to pass information to the Table. After getting the data from the backend, Table also needs to pass how many pages are needed to the Pagination components. There are lots of props being passed around, also Table and Pagination are both passing props to each other, which seems a bit messy. 
**Solution:**
Move all API calling methods to the SearchPage component, the resulted data is passed to the Table as a prop. 
This leads to a new issue:
- The Table originally contains data as a state and changes this state when sorting data. However, it cannot modify its props. 
To solve that, the original sort function is split into two functions. Before …

[CMLG-015] Refactor the code in Table and SearchPage components

---

src/components/Pagination.js
src/components/SearchPage.js

Issue:
When user only wants to view only 10 results per page, needs a method to view the next 10 results.
Solution:
Add Pagination which allows user to get more results.
Pagination not visible if only a single page of results
(To test change the url fetch to the dev backend)
Risk/Note: CSS and caching to be implemented still.
Reviewed by Emily, Kevin, Eileen, Yujia, Dave

[CMLG-015] Implement the basic functionality of the table pagination

---

src/components/SearchBar.js

Issue:
Users need to click on the search bar in order to start searching now, but we want the user to search straightforward when they load the page.
Solution: 
Add autoFocus to the search bar.
Risk:
Unknown
Reviewed by:
Kevin, Emily, Yujia, Annie, Dave

[CMLG-019] Add auto focus to the search bar when we load the search page

---

src/components/Pagination.js
src/components/RowsPerPageToggleButton.js
src/components/SearchPage.js
src/components/Table.js

Issue:
When backend only returns 10 rows of data, the frontend cannot handle sorting itself.
Passing sorting request back to backend may result in too many API requests.
Solution:
Frontend always asks for all the data from the backend, i.e. set rows per page to be "all" for each request. If the user wants to see only 10 rows per page, frontend will calculate the index of the data needs to be displayed and only display the required ones.
Risk:
The backend has functionalities that frontend currently don't need.
Getting all the data means it will take longer for the website to respond when data gets larger.
Reviewed by:
Dave, Annie, Eileen, Kevin, Yujia

[CMLG-015] Display 10 rows using frontend

---

src/components/css/SelectCol.css

Issue:
1. The users can't see all the options when the window's height is smaller than the card's size.
2. Try to solve the issue when the window height decrease, the card will move up and cover the selectCol button.
Solution:
1. Resize the card make it smaller than the window size and enable the scrollable.
2. Change the top be fixed px rather than the percentage.
Risk:  
No risk currently.
Reviewed By: 
Emily, Eileen, Annie, Kevin, Dave

[CMLG-013] Fix SelectCol Responsive Bugs

---

src/components/SearchPage.js

Issue:
When the window size is small, the toggle button group component is pushed to the next line. It's not lined up with the select language component.
Soluiton:
Add another div around both select language component and toggle button group, add css "display: flow-root".
Risk:
/
Reviewed by:
Eileen, Dave, Kevin, Yujia, Annie

[CMLG-015] Add css to the toggle button group

---

src/components/SearchPage.js
src/components/Table.js

Issue:
When the user switches between "all" and "10 rows", the totalPages state is not updated.
Solution:
Calculate the new totalPages every time the user switches between "all" and "10 rows".
Adding some todos comments for future changes.
Risk:
/
Reviewed by:
Annie, Eileen, Dave, Yujia, Kevin

[CMLG-015] fix bugs in render table pagination

---

src/components/RowsPerPageToggleButton.js
src/components/SearchPage.js
src/css/RowsPerPageToggleButton.css

Issue:
There is a bug about the active button. If you turn on on the dark mode after you click the "all" button, in dark mode, the "10 rows" button is highlighted instead of the "all" button. The details is stated in Github Issues #67
Solution:
Having an active state for the toggle button group.
Risk:
Unknown
Reviewed by:
Annie, Eileen, Dave, Yujia, Emily

[CMLG-026]Solve the toggle button dark mode bug by having a state

---

src/components/HeaderBar.js
src/components/SelectCol.js

Issue:
When we're open the select col component and click on other page, it will produce a null type error.
Solution:
Check if the ref node exist.
Risk:
Change in selectcol component.
Reviewed by:
Emily, Yujia, Kevin, Annie, Dave

[CMLG-027] Fix select col type error

---

src/components/HelloWorld.js
src/components/WelcomePage.js
src/css/WelcomePage.css

Issue :
On dark mode, when you hover over the button, the colours are not inverted.
We want a white background with black text but we previously had a grey background with white text.
Solution :
Added .btn-dark-mode:hover in WelcomPage.css to invert the colours when you hover over it.
Risk :
Button colour could be incorrect
Reviewed by :
Dave, Annie, Kevin, Eileen, Hayoon, Clarissa

[CMLG-035] Dark Mode Start Button
